local-gadget: Add oomkill trace gadget
inspektor-gadget/inspektor-gadget pull request #1029
Opened 2022-10-11 11:03 UTC by blanquicet

2022-10-13 20:58 UTC, mauriciovasquezbernal approved these changes
LGTM. I tested with the yaml you're using for the integration test and it worked fine.

2022-10-13 20:58 UTC, mauriciovasquezbernal commented on integration/local-gadget/trace_oomkill_test.go
> +		Name:         "StartOomkilGadget",
```suggestion
		Name:         "StartOomkillGadget",
```

2022-10-13 21:47 UTC, mauriciovasquezbernal requested changes
Please update imports names before merging. (https://github.com/inspektor-gadget/inspektor-gadget/pull/1040).

2022-10-14 11:34 UTC, blanquicet commented
Rebased and updated.

2022-10-14 15:49 UTC, mauriciovasquezbernal approved these changes
LGTM. Thanks!

2022-10-14 15:54 UTC, merged